build using TypeScript instead of babel (#123)
* Support for TypeScript (tsc) builds.
usage: `tsc` or `npm run build-tsc`
Currently treats errors as warnings.
TypeScript build outputs will go into a new `built` folder
The `checkJs` compiler option hasn't been enabled yet, so only 6 errors generated:

src/override.js(113,42): error TS8010: 'types' can only be used in a .ts file.
src/override.js(113,59): error TS8010: 'types' can only be used in a .ts file.
test/unit/extendDescriptor.js(82,7): error TS1128: Declaration or statement expected.
test/unit/extendDescriptor.js(89,7): error TS1128: Declaration or statement expected.
test/unit/mixin.spec.js(22,10): error TS1109: Expression expected.
test/unit/mixin.spec.js(37,17): error TS1109: Expression expected.

* Remove type declaration override.js

Fixes TypeScript messages:
src/override.js(113,42): error TS8010: 'types' can only be used in a .ts file.
src/override.js(113,59): error TS8010: 'types' can only be used in a .ts file.

* Fix auto-generated semi in extendDescriptor.js

I'm guessing some tool inserted semicolons where JavaScript *might* infer them.

* Workaround decorator on class expression in test/unit/mixin.spec.js

TypeScript can't support this right now.   Known issue.

* Avoid  `...arguments` in util.js

the keyword `arguments` is special, it's not really an array.

Typescript doesn't generate good code for this case.  Fixes #122

* Rollback change that turned on --checkJs

* Enable stricter tsc error checking

* tsc - map import lib/* -> src/*

See TypeScript [module-resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) for details.
This change only changes how tsc performs module resolution, not code generation.  Specifically it doesn't move the built directories around.

* add rootDir to package.ts

* include key files needed for tests to run

* use correct import style for each package in tests

* Use Array.slice.prototype.call()

* fix import statement in test.spec.js
disable tsc `checkJs` option to quiet warnings

* suppress unreachable code error in tsc

* build-tsc build script cleanup

With this change, both `npm run build` and `npm run build-ts` put their output in the __`lib`__ directory.  This allows us to compare behavior between the two versions of the library using `npm test` in either case.

Right now, I'm getting 0 failures with the `build` (babel) version of the library, and 20 failures with the `build-tsc` (TypeScript) version.

- clean out the built directory before tsc
- remove hack to ignore erros from tsc
- checkin vscode launch/debug files
- compile _only_ the `src` directory with tsc
- switch back to default import of sinonChai in test.spec.js

* Include babel-based build in `prepublish` script

Should fix the Travis CI/Appveyor failures.

* chore: Updates from code review

Cleaning up a few unneeded dependencies & scripts